BoevaLab/CanSig

.github/workflows/docs.yml, docs/Makefile, docs/conf.py, docs/index.rst, docs/make.bat
This PR sets the simplest possible Sphinx configuration, so that it gets automatically deployed to GitHub Pages.
=> Sphinx documentation on GitHub Pages

.github/workflows/docs.yml
This PR changes the name of the branch, as the GitHub action was never started.
=> Fix docs generation

.github/workflows/build.yml, README.md, docs/conf.py, docs/index.rst, docs/source/cansig.rst, docs/source/modules.rst, requirements-dev.txt
This PR extends the documentation and moves some of the ReadMe parts into the Sphinx documentation.
=> Restructure the documentation

.github/workflows/build.yml, .pre-commit-config.yaml, README.md, docs/conf.py, docs/contributing.rst, docs/index.rst, pyproject.toml, requirements-dev.txt, setup.cfg
This PR adds flake8 (PEP8 compliance) and pytype (type checking) to the CI.
Moreover, it extends the documentation, giving the instructions how to develop the package with these tools.
=> Extend CI pipeline

README.md, docs/contributing.rst, docs/index.rst, docs/preprocessing.rst
This small PR slightly improves documentation.
=> Improve documentation

cansig/tutorial.py, docs/preprocessing.rst, setup.cfg
Hi all,
this is the preprocessing tutorial. There are still a lot of todos and it probably needs some work language-wise.
=> Preprocessing tutorial

docs/conf.py
This PR is tiny: it adds a GitHub link to the documentation.
=> Add GitHub link

cansig/tutorial.py
This PR introduces a function downloading the data to the given path. It supports verbose mode, with printing out progress bar.
This will be useful for:
- Downloading the raw data for the preprocessing tutorial.
- Downloading the processed data for the pipeline tutorial.
- Downloading custom gene sets.
=> Data downloading function

cansig/cluster/leiden.py, cansig/run/postprocessing.py
this fixes the wrong initialisation of the gsea config that didn't take into consideration the provided arguments and a future warning in leiden
=> Fix bug with GSEA initialization

docs/index.rst, docs/pipeline-advanced.rst, docs/source/cansig.cluster.rst, docs/source/cansig.interface.rst, docs/source/cansig.metaanalysis.rst, docs/source/cansig.models.rst, docs/source/cansig.run.rst
Updated the documentation so it fit the new plotting utilities + updated the description of the output folder, which was outdated
=> Added documentation for plotting

cansig/filesys.py, cansig/gsea.py, cansig/run/pipeline.py, cansig/run/postprocessing.py, docs/index.rst, docs/pipeline-advanced.rst, docs/source/cansig.cluster.rst, docs/source/cansig.interface.rst, docs/source/cansig.metaanalysis.rst, docs/source/cansig.models.rst, docs/source/cansig.run.rst
This enables the signatures to be automatically saved, so that the promise of getting "de novo signatures" is fulfilled
=> Saving automatically the results of the differential gene expression analysis

cansig/metaanalysis/heatmap.py, cansig/run/pipeline.py
This PR resolves #17 . While it's not a 100% principled solution, this heuristics should work well-enough for the final figures.
=> Fix heatmap resolution

cansig/run/download.py
This tiny PR adds downloading the dataset needed to run the pipeline.
=> Download the tutorial dataset

cansig/plotting/plotting.py, requirements.txt, setup.cfg
This PR adds the plotting of UMAP with PCA as insets to the plotting module of cansig.
=> Adds plotting of umap with pca as inset.

cansig/cnvanalysis/differentialcnvs.py, cansig/filesys.py, cansig/gsea.py, cansig/run/pipeline.py, cansig/run/postprocessing.py, requirements.txt, setup.cfg
This small PR follows our discussion this morning - it automatically saves (if the savesig flag is on) the scores per cell associated to the de novo signatures found and the correlation between these signatures.
=> Score cells according to de novo signatures and save correlation between signatures

cansig/run/pipeline.py
there was a bug in the scatter plot configuration
=> correcting plotting bug

setup.cfg
Super small PR just to correct the setup.cfg for PyPi
=> correcting setup bug

cansig/metaanalysis/repr_directory.py, cansig/models/scvi.py, cansig/plotting/plotting.py
small PR to remove copying to avoid OOM + changed the repr dir objective functino from sum to mean (the complexity wasn't contributing right now...)
=> Making everything inplace

cansig/_preprocessing/infercnv.py, cansig/_preprocessing/main.py, cansig/_preprocessing/scoring.py, cansig/_preprocessing/utils.py, tests/preprocessing/test_infercnv.py, tests/preprocessing/test_scoring.py, tests/preprocessing/test_utils.py
This PR adds a check to ensure that at enough malignant cells were added to run infercnv and removes the NormalizationConfig because nobody wants to customize target_sum.
=> Removed normalize config and inlined code in main

README.md, docs/cansig-for-python-coders.rst, docs/conf.py, docs/contributing.rst, docs/formatting-data.rst, docs/index.rst, docs/interpretation.rst, docs/preprocessing.rst
This (minor) PR adjusts the documentation. In particular:
- We drop (outdated) release number.
- The section names are now shorter, better fitting into the menu on the top of the page.
- The links look better.
=> Minor changes to documentation

cansig/_preprocessing/annotation.py, cansig/_preprocessing/data.py, cansig/_preprocessing/infercnv.py, cansig/_preprocessing/main.py, cansig/_preprocessing/plotting.py, cansig/_preprocessing/quality_control.py, cansig/_preprocessing/scoring.py, cansig/_preprocessing/subclonal.py, docs/preprocessing.rst, tests/preprocessing/test_annotation.py, tests/preprocessing/test_main.py, tests/preprocessing/test_quality_control.py
This PR does two things:
- Updates the documentation in preprocessing.
- Adds qc and cnv plots to preprocessing.
=> Plotting+docs

docs/index.rst
This PR moves the navigation section upwards.
=> Move navigation section upwards

cansig/gsea.py, cansig/run/pipeline.py, tests/test_gsea.py
This PR resolves #63: checking whether the GMT file exists and if the format looks right.
=> Add GMT file validation

src/cansig/__init__.py, src/cansig/_preprocessing/data.py, src/cansig/_preprocessing/infercnv.py, src/cansig/_preprocessing/main.py, src/cansig/_preprocessing/quality_control.py, src/cansig/_preprocessing/scoring.py, src/cansig/integration/base/model.py, src/cansig/integration/model.py, src/cansig/integration/module/batcheffectvae.py, src/cansig/integration/module/cnvvae.py, src/cansig/integration/module/vae.py, src/cansig/integration/training/trainer.py, src/cansig/integration/training/training_plan.py, src/cansig/metaanalysis/repr_directory.py, src/cansig/models/cansig.py, src/cansig/run/download.py, src/cansig/run/heatmap.py, src/cansig/run/integration.py, src/cansig/run/pipeline.py, src/cansig/run/postprocessing.py, tests/preprocessing/test_annotation.py, tests/preprocessing/test_data.py, tests/preprocessing/test_infercnv.py, tests/preprocessing/test_main.py, tests/preprocessing/test_quality_control.py, tests/preprocessing/test_scoring.py, tests/test_gsea.py
This PR turns CanSig into a betaVAE.
=> Betacansig

src/cansig/_preprocessing/_infercnv.py, src/cansig/_preprocessing/annotation.py, src/cansig/_preprocessing/infercnv.py, src/cansig/_preprocessing/main.py, src/cansig/_preprocessing/plotting.py, src/cansig/integration/module/batcheffectvae.py, src/cansig/integration/module/vae.py, tests/preprocessing/test_annotation.py, tests/preprocessing/test_infercnv.py, tests/preprocessing/test_main.py, tests/preprocessing/utils.py
Fixed bug in preprocessing and removed normalization.
=> Infercnv patch

src/cansig/metasignatures/clustering.py, src/cansig/run/metasignatures.py, src/cansig/run/pipeline.py
I wasn't passing threshold as an arg in the metasignature which obv is wrong + put cansig as default
=> false call

src/cansig/run/split.py
This script splits a given data set into two by a specified column (corresponding to different patients).
=> Script to split a data set into two

src/cansig/cluster/leiden.py, src/cansig/metasignatures/clustering.py, src/cansig/metasignatures/utils.py, src/cansig/run/metasignatures.py, src/cansig/run/pipeline.py
This PR fixes some minor issues with the metasignatures code and asks some questions (the method is sophisticated enough that I didn't follow).
=> Minor fixes to metasignatures

src/cansig/run/download.py
This PR adds the link to the data set used in the tutorial.
=> Add simulated dataset

docs/pipeline-advanced.rst, docs/preprocessing.rst
This PR updates the documentation regarding the advanced pipeline usage.
=> Update the documentation

src/cansig/metasignatures/clustering.py, src/cansig/metasignatures/utils.py, src/cansig/run/metasignatures.py
This PR adds the automatic selection of the latent space that is used to visualize the meta-memberships.
=> Adding selection of latent space, highlighting the meta-signatures.

src/cansig/metasignatures/clustering.py, src/cansig/models/cansig.py, src/cansig/run/metasignatures.py, src/cansig/run/pipeline.py
This PR adds the possibility for the user to perform the analysis with a fixed k rather than with the correlation threshold
=> fixed k possibility

src/cansig/metasignatures/clustering.py, src/cansig/metasignatures/consensusclustering.py, src/cansig/metasignatures/utils.py, src/cansig/run/metasignatures.py, src/cansig/run/pipeline.py
This PR implements consensus clustering (CSPA) for metasignature discovery
=> Consensus clustering for metasignature discovery
